-- Update password for admin user
-- Password: password123
-- Hash generated by Laravel Hash::make('password123')

UPDATE `staff` SET `password_hash` = '$2y$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4XyQ1.MUxyaX3BdC' WHERE `username` = 'admin';

-- If you want to set same password for all test users:
-- UPDATE `staff` SET `password_hash` = '$2y$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4XyQ1.MUxyaX3BdC';
